language: node_js
node_js:
  - v8
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
env:
  global:
    - GH_TOKEN: 52adec08b1c92837cc82e518dafb8fc4c2902917
    - NPM_TOKEN: 89b19f78-8cd9-460b-bf59-d1e5bfa17d03