language: node_js
node_js:
  - v6
  - v8
script:
  - npm run lint
  - npm run test
deploy:
  provider: script
  script:
    - npm run build
    - git config --global user.name "TravisCI"
    - git config --global user.email "commitizen@travis.ci"
    - npm run semantic-release
  on:
    branch: master
    node: v8