language: node_js
node_js:
  - v8
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
env:
  global:
    - GH_TOKEN: 6722b4f67170deae79aced25542a9d834f492f1d
    - NPM_TOKEN: 89b19f78-8cd9-460b-bf59-d1e5bfa17d03