language: node_js
node_js:
  - v6
  - v8
script:
  - npm run lint
  - npm run test
deploy:
  provider: script
  script:
    - npm run build
    - npm run semantic-release
  on:
    tags: true
    node: v8